[target.x86_64-apple-darwin]
dockerfile = "cross-toolchains/docker/Dockerfile.x86_64-apple-darwin-cross"
[target.aarch64-apple-darwin]
dockerfile = "cross-toolchains/docker/Dockerfile.aarch64-apple-darwin-cross"