name: prql-java-test

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]

jobs:
  junit-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: build for x86_64-unknown-linux-gnu
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cd ./
          cargo build --release --target=x86_64-unknown-linux-gnu
          cp -f ./prql-java/target/x86_64-unknown-linux-gnu/release/libprql4j.so ./prql-java/java-api/src/main/resources/libprql4j-linux64.so
      - name: Maven test
        run: cd ./java-api/ && ./mvnw test
